name: PokeMe
options:
  bundleIdPrefix: com.pokeme
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: ""

targets:
  PokeMe:
    type: application
    platform: iOS
    sources:
      - PokeMe
    settings:
      base:
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
        GENERATE_INFOPLIST_FILE: YES
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
        PRODUCT_BUNDLE_IDENTIFIER: com.pokeme.app
        PRODUCT_NAME: PokeMe
        SWIFT_EMIT_LOC_STRINGS: YES

  PokeMeTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - PokeMeTests
    dependencies:
      - target: PokeMe
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.pokeme.app.tests
