runtime: python312

instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 2

env_variables:
  JWT_SECRET: "your-secret-key-change-in-production"

handlers:
  - url: /.*
    script: auto
    secure: always

entrypoint: gunicorn -b :$PORT main:app
